swift_version = "5.0"
platform :ios, '10.0'

use_frameworks!

target 'ZigzagKit_Example' do
  pod 'ZigzagKit', :path => '../'

  target 'ZigzagKit_Tests' do
    inherit! :search_paths

    
  end
end
