swift_version = "3.0"
platform :ios, '9.0'

use_frameworks!

target 'ZigzagKit_Example' do
  pod 'ZigzagKit', :path => '../'
  pod 'AssociatedValues', "3.0.0"

  target 'ZigzagKit_Tests' do
    inherit! :search_paths

    
  end
end
